// <auto-generated />
namespace WebThiThuBangLaiOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateRequiredOfQuestion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateRequiredOfQuestion));
        
        string IMigrationMetadata.Id
        {
            get { return "202412181840502_updateRequiredOfQuestion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
